// react-communication/src/SelectSize.js
import './App.css';
import React from "react";

function SelectSize({setSelectedSize}) {

    function onSelectSize(size) {
        setSelectedSize(size)
    }

    return (
        <>
            <div>
                <h3>Select Size</h3>
            </div>
            <div>
                <input type="number" min="39" max="47" step="1" onChange={event => onSelectSize(event.target.value)}/>
            </div>

        </>
    );
}

export default SelectSize;

// angular-communication/src/app/select-size/select-size.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-select-size',
  templateUrl: './select-size.component.html',
  styleUrls: ['./select-size.component.scss']
})
export class SelectSizeComponent {

  @Output()
  public selectedSize: EventEmitter<number> = new EventEmitter<number>();

  constructor() {
  }

  public onSelectSize(event: Event): void {
    this.selectedSize.emit(Number((event.target as HTMLInputElement).value));
  }

}

<div>
  <h3>Select Size</h3>
</div>
<div>
  <input type="number" [min]="39" [max]="47" [step]="1" (change)="onSelectSize($event)" />
</div>
