// angular-communication/src/app/select-color/select-color.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-select-color',
  templateUrl: './select-color.component.html',
  styleUrls: ['./select-color.component.scss']
})
export class SelectColorComponent {

  @Output()
  public selectedColor: EventEmitter<string> = new EventEmitter<string>();

  public colors = ['white', 'black', 'yellow', 'red'];

  constructor() {
  }

  public onSelectColor(event: Event): void {
    this.selectedColor.emit((event.target as HTMLInputElement).value);
  }

}

<div>
  <h3>Select color</h3>
</div>
<div>
  <select (change)="onSelectColor($event)">
    <option *ngFor="let color of colors" [value]="color">
      {{color}}
    </option>
  </select>
</div>

// react-communication/src/SelectColor.js
import './App.css';
import React from "react";

function SelectColor({setSelectedColor}) {

    function onSelectColor(color) {
        setSelectedColor(color)
    }

    const colors = ['white', 'black', 'yellow', 'red'];

    return (
        <>
            <div>
                <h3>Select color</h3>
            </div>
            <div>
                <select onChange={event => onSelectColor(event.target.value)}>
                    {
                        colors.map(color => <option value={color} key={color}>{color}</option>)
                    }
                </select>
            </div>
        </>
    );
}

export default SelectColor;
